### ISSUE TITLE
Clicking on the TOC on the left expands everything

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb-docs#261] opened 2017-02-07 07:01 UTC
Hi,

**What is happening?**

If you click on "SQL Reference" in the TOC on the left, all the sections open up and I lose my place in the TOC. It is quite annoying.

**What is expected?**

Only the section being clicked on i.e. "SQL Reference" should expand.

I am looking at this version: http://orientdb.com/docs/2.2/ 

Scott

**Comment by santo-it** [comment] 2017-02-07 09:40
Hi @smolinari ,

Thanks for opening this issue. Yeah, we noticed it as well. This is happening since a few days. We are investigating the possible root cause

Thanks,

**Comment by santo-it** [comment] 2017-02-13 22:43
Refreshing the page from the browser "refresh" button (one or two times) seems to solve the issue

**Comment by smolinari** [comment] 2017-02-14 04:55
That can't be the solution though.

Scott

**Comment by santo-it** [comment] 2017-02-22 08:13
Hi @smolinari ,

We fixed this. The issue was caused by the integration with a caching system
I'm closing this now. Please comment if you still experience any problem

Thanks again for your patience

**Closed by santo-it** 2017-02-22 08:13 UTC
Labels: bug, PBL1

**Comment by smolinari** [comment] 2017-02-22 10:34
Very good! I can confirm the problem is fixed. Thanks!

Scott
